CONTIKI_PROJECT = test-lmciot
CONTIKI = ../../../..
TARGET ?= mikro-e

APPS += letmecreateiot

all: $(CONTIKI_PROJECT)

distclean: cleanall

cleanall:
	rm -f symbols.*

include $(CONTIKI)/Makefile.include
